### ISSUE TITLE
Render function in vue3

### ISSUE THREAD

**Issue by Lx4** [bencodezen/production-grade-vue#2]
Hi,

Currently doing the FEM course, thank you ! :)
In your doc for vue3 render you have 
```<script>
import { h } from 'vue'

export default {
  render(createElement) {
    return createElement('h1', 'Hello Frontend Masters!’)
  }
}
</script>
```

Don't you have to use h inside your render function like you explain in your video?
Thanks
Franck

**Comment by bencodezen** [comment]
Good catch! Sorry for the delay in responding to this. My GitHub notifications buried me over the pandemic. 😅 

I'll update that shortly!
